# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nick Martin
title: Computer Wizard
email: Nick.Martin.Pro@gmail.com
website: NickM.Me

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: nicholas-martin-972a8839
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Having successfully transitioned into the industrial field, I leverage my strong background in IT to excel in designing, deploying, and optimizing next-generation systems. 
  Driven by innovation, collaboration, and continuous learning, I thrive among excellence-focused professionals and look forward to creating impactful solutions across diverse industrial environments.

  I am most skilled in: <mark>Information</mark> and <mark>Technology</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: HMI Design for a Wood Treating Plant 
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: #>
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Developed operator-friendly interfaces and assisted in creating logic for an advanced wood treating operation

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Embry Automation and Controls, Evansville, IN
        link: embryenterprises.com
        # link_text: boringcompany.com
        sub_title: Automation Specialist
        caption: June 2023 - January 2025
        quote: >
          Your average every day expert of wood treating
        description: | # this will include new lines to allow paragraphs
            Oversaw end-to-end development and integration of complex automation solutions—ranging from PLC programming and HMI design to SCADA configuration and instrumentation setup—ensuring seamless functionality, adherence to compliance standards, and enhanced efficiency within diverse industrial client locations.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ivy Tech
        caption: 2016
        sub_title: BSc Computer Science
        quote: >
          Founded in 1963, Ivy Tech Community College is Indiana’s largest public postsecondary institution and the nation’s largest singly accredited statewide community college system. Known for its strong focus on workforce development, affordability, and flexible learning paths, Ivy Tech plays a vital role in connecting students to in-demand careers and four-year university opportunities across the state.
        description: | # this will include new lines to allow paragraphs
          During my time at Ivy Tech, I focused on network administration, where I developed a strong foundation in IT systems, troubleshooting, and infrastructure management. These skills became the springboard for my transition into controls engineering, where I now apply that technical background to industrial automation and system integration.

          While I didn’t study controls directly in college, my experience managing networks and solving real-world problems prepared me to adapt quickly and learn on the job. That adaptability continues to be one of my biggest strengths in the field.

          Interesting fact, I was runner up for *School President* in 2014.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Building a DIY turtlebot
      - Building a dual stick controlled Omniwheel robot 
      - Home Automaton

   #  Look at this cool image  
   #  ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
